"""display period

Revision ID: 10451efbedde
Revises: 6e90d7baf239
Create Date: 2026-09-26 10:54:22.004819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10451efbedde'
down_revision: Union[str, Sequence[str], None] = '6e90d7baf239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('display_devices', sa.Column('period', sa.String(length=10), server_default='daily', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('display_devices', 'period')
    # ### end Alembic commands ###
