"""initial schema

Revision ID: 6e90d7baf239
Revises: 
Create Date: 2026-09-26 06:40:51.818882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e90d7baf239'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('id_alias',
    sa.Column('alias', sa.String(length=40), nullable=False),
    sa.Column('canonical', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_table('plan_produksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ob_bcm', sa.Float(), nullable=True),
    sa.Column('coal_ton', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_produksi_site'), 'plan_produksi', ['site'], unique=False)
    op.create_table('pm_interval',
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('interval_hm', sa.Float(), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_table('sites',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('standby_group',
    sa.Column('reason_code', sa.Integer(), nullable=False),
    sa.Column('grp', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('reason_code')
    )
    op.create_table('tank_site',
    sa.Column('tank', sa.String(length=40), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tank')
    )
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Float(), nullable=True),
    sa.Column('uoa', sa.Float(), nullable=True),
    sa.Column('mtbs', sa.Float(), nullable=True),
    sa.Column('mttr', sa.Float(), nullable=True),
    sa.Column('sched_down', sa.Float(), nullable=True),
    sa.Column('pm_accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site', 'year', 'month')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('all_sites', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('display_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site_code', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_code'], ['sites.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_uploads_month'), 'uploads', ['month'], unique=False)
    op.create_table('user_sites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['site_code'], ['sites.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_code')
    )
    op.create_table('dim_unit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_unit_month'), 'dim_unit', ['month'], unique=False)
    op.create_index(op.f('ix_dim_unit_site'), 'dim_unit', ['site'], unique=False)
    op.create_index(op.f('ix_dim_unit_unit_id'), 'dim_unit', ['unit_id'], unique=False)
    op.create_index(op.f('ix_dim_unit_upload_id'), 'dim_unit', ['upload_id'], unique=False)
    op.create_table('dq_findings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('sheet', sa.String(length=40), nullable=False),
    sa.Column('row_ref', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_findings_site'), 'dq_findings', ['site'], unique=False)
    op.create_index(op.f('ix_dq_findings_upload_id'), 'dq_findings', ['upload_id'], unique=False)
    op.create_table('fact_coal_tiket',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_dt', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=2), nullable=False),
    sa.Column('ticket_id', sa.String(length=60), nullable=True),
    sa.Column('supplier', sa.String(length=80), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('seam', sa.String(length=40), nullable=True),
    sa.Column('dt_unit', sa.String(length=40), nullable=True),
    sa.Column('loader', sa.String(length=40), nullable=True),
    sa.Column('ton', sa.Float(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('dist_h', sa.Float(), nullable=True),
    sa.Column('dist_v', sa.Float(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_coal_tiket_date'), 'fact_coal_tiket', ['date'], unique=False)
    op.create_index(op.f('ix_fact_coal_tiket_month'), 'fact_coal_tiket', ['month'], unique=False)
    op.create_index(op.f('ix_fact_coal_tiket_site'), 'fact_coal_tiket', ['site'], unique=False)
    op.create_index(op.f('ix_fact_coal_tiket_upload_id'), 'fact_coal_tiket', ['upload_id'], unique=False)
    op.create_table('fact_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=2), nullable=False),
    sa.Column('week', sa.String(length=8), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('operator', sa.String(length=120), nullable=True),
    sa.Column('time_start', sa.Float(), nullable=True),
    sa.Column('time_end', sa.Float(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('hm_start', sa.Float(), nullable=True),
    sa.Column('hm_end', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('category', sa.String(length=1), nullable=False),
    sa.Column('reason_code', sa.Integer(), nullable=True),
    sa.Column('reason_text', sa.String(length=120), nullable=True),
    sa.Column('down_type', sa.String(length=12), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_event_date'), 'fact_event', ['date'], unique=False)
    op.create_index(op.f('ix_fact_event_month'), 'fact_event', ['month'], unique=False)
    op.create_index(op.f('ix_fact_event_site'), 'fact_event', ['site'], unique=False)
    op.create_index(op.f('ix_fact_event_unit_id'), 'fact_event', ['unit_id'], unique=False)
    op.create_index(op.f('ix_fact_event_upload_id'), 'fact_event', ['upload_id'], unique=False)
    op.create_table('fact_fuel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=2), nullable=False),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('unit_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('outlier', sa.Boolean(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_fuel_date'), 'fact_fuel', ['date'], unique=False)
    op.create_index(op.f('ix_fact_fuel_month'), 'fact_fuel', ['month'], unique=False)
    op.create_index(op.f('ix_fact_fuel_site'), 'fact_fuel', ['site'], unique=False)
    op.create_index(op.f('ix_fact_fuel_unit_id'), 'fact_fuel', ['unit_id'], unique=False)
    op.create_index(op.f('ix_fact_fuel_upload_id'), 'fact_fuel', ['upload_id'], unique=False)
    op.create_table('fact_fuel_receipt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=2), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('operator', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('dn_no', sa.String(length=60), nullable=True),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_fuel_receipt_date'), 'fact_fuel_receipt', ['date'], unique=False)
    op.create_index(op.f('ix_fact_fuel_receipt_month'), 'fact_fuel_receipt', ['month'], unique=False)
    op.create_index(op.f('ix_fact_fuel_receipt_site'), 'fact_fuel_receipt', ['site'], unique=False)
    op.create_index(op.f('ix_fact_fuel_receipt_upload_id'), 'fact_fuel_receipt', ['upload_id'], unique=False)
    op.create_table('fact_ritase_jam',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_hauler', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour_slot', sa.String(length=5), nullable=False),
    sa.Column('shift', sa.String(length=2), nullable=False),
    sa.Column('hauler', sa.String(length=40), nullable=False),
    sa.Column('hauler_model', sa.String(length=80), nullable=True),
    sa.Column('muatan', sa.Float(), nullable=False),
    sa.Column('loader', sa.String(length=40), nullable=False),
    sa.Column('loader_model', sa.String(length=80), nullable=True),
    sa.Column('material', sa.String(length=80), nullable=True),
    sa.Column('material_group', sa.String(length=5), nullable=False),
    sa.Column('pit', sa.String(length=120), nullable=True),
    sa.Column('disposal', sa.String(length=120), nullable=True),
    sa.Column('dist_v', sa.Float(), nullable=True),
    sa.Column('dist_h', sa.Float(), nullable=True),
    sa.Column('rit', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('unit_vol', sa.String(length=4), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_ritase_jam_date'), 'fact_ritase_jam', ['date'], unique=False)
    op.create_index(op.f('ix_fact_ritase_jam_month'), 'fact_ritase_jam', ['month'], unique=False)
    op.create_index(op.f('ix_fact_ritase_jam_site'), 'fact_ritase_jam', ['site'], unique=False)
    op.create_index(op.f('ix_fact_ritase_jam_upload_id'), 'fact_ritase_jam', ['upload_id'], unique=False)
    op.create_table('fact_stoppage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_shift', sa.String(length=2), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('sm_hours', sa.Float(), nullable=False),
    sa.Column('usm_hours', sa.Float(), nullable=False),
    sa.Column('main_reason', sa.String(length=120), nullable=True),
    sa.Column('hm_start', sa.Float(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_stoppage_month'), 'fact_stoppage', ['month'], unique=False)
    op.create_index(op.f('ix_fact_stoppage_site'), 'fact_stoppage', ['site'], unique=False)
    op.create_index(op.f('ix_fact_stoppage_unit_id'), 'fact_stoppage', ['unit_id'], unique=False)
    op.create_index(op.f('ix_fact_stoppage_upload_id'), 'fact_stoppage', ['upload_id'], unique=False)
    op.create_table('upload_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=40), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('dq_summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'site_code')
    )
    op.create_index(op.f('ix_upload_sites_month'), 'upload_sites', ['month'], unique=False)
    op.create_index(op.f('ix_upload_sites_site_code'), 'upload_sites', ['site_code'], unique=False)
    op.create_index(op.f('ix_upload_sites_status'), 'upload_sites', ['status'], unique=False)
    op.create_index(op.f('ix_upload_sites_upload_id'), 'upload_sites', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_sites_upload_id'), table_name='upload_sites')
    op.drop_index(op.f('ix_upload_sites_status'), table_name='upload_sites')
    op.drop_index(op.f('ix_upload_sites_site_code'), table_name='upload_sites')
    op.drop_index(op.f('ix_upload_sites_month'), table_name='upload_sites')
    op.drop_table('upload_sites')
    op.drop_index(op.f('ix_fact_stoppage_upload_id'), table_name='fact_stoppage')
    op.drop_index(op.f('ix_fact_stoppage_unit_id'), table_name='fact_stoppage')
    op.drop_index(op.f('ix_fact_stoppage_site'), table_name='fact_stoppage')
    op.drop_index(op.f('ix_fact_stoppage_month'), table_name='fact_stoppage')
    op.drop_table('fact_stoppage')
    op.drop_index(op.f('ix_fact_ritase_jam_upload_id'), table_name='fact_ritase_jam')
    op.drop_index(op.f('ix_fact_ritase_jam_site'), table_name='fact_ritase_jam')
    op.drop_index(op.f('ix_fact_ritase_jam_month'), table_name='fact_ritase_jam')
    op.drop_index(op.f('ix_fact_ritase_jam_date'), table_name='fact_ritase_jam')
    op.drop_table('fact_ritase_jam')
    op.drop_index(op.f('ix_fact_fuel_receipt_upload_id'), table_name='fact_fuel_receipt')
    op.drop_index(op.f('ix_fact_fuel_receipt_site'), table_name='fact_fuel_receipt')
    op.drop_index(op.f('ix_fact_fuel_receipt_month'), table_name='fact_fuel_receipt')
    op.drop_index(op.f('ix_fact_fuel_receipt_date'), table_name='fact_fuel_receipt')
    op.drop_table('fact_fuel_receipt')
    op.drop_index(op.f('ix_fact_fuel_upload_id'), table_name='fact_fuel')
    op.drop_index(op.f('ix_fact_fuel_unit_id'), table_name='fact_fuel')
    op.drop_index(op.f('ix_fact_fuel_site'), table_name='fact_fuel')
    op.drop_index(op.f('ix_fact_fuel_month'), table_name='fact_fuel')
    op.drop_index(op.f('ix_fact_fuel_date'), table_name='fact_fuel')
    op.drop_table('fact_fuel')
    op.drop_index(op.f('ix_fact_event_upload_id'), table_name='fact_event')
    op.drop_index(op.f('ix_fact_event_unit_id'), table_name='fact_event')
    op.drop_index(op.f('ix_fact_event_site'), table_name='fact_event')
    op.drop_index(op.f('ix_fact_event_month'), table_name='fact_event')
    op.drop_index(op.f('ix_fact_event_date'), table_name='fact_event')
    op.drop_table('fact_event')
    op.drop_index(op.f('ix_fact_coal_tiket_upload_id'), table_name='fact_coal_tiket')
    op.drop_index(op.f('ix_fact_coal_tiket_site'), table_name='fact_coal_tiket')
    op.drop_index(op.f('ix_fact_coal_tiket_month'), table_name='fact_coal_tiket')
    op.drop_index(op.f('ix_fact_coal_tiket_date'), table_name='fact_coal_tiket')
    op.drop_table('fact_coal_tiket')
    op.drop_index(op.f('ix_dq_findings_upload_id'), table_name='dq_findings')
    op.drop_index(op.f('ix_dq_findings_site'), table_name='dq_findings')
    op.drop_table('dq_findings')
    op.drop_index(op.f('ix_dim_unit_upload_id'), table_name='dim_unit')
    op.drop_index(op.f('ix_dim_unit_unit_id'), table_name='dim_unit')
    op.drop_index(op.f('ix_dim_unit_site'), table_name='dim_unit')
    op.drop_index(op.f('ix_dim_unit_month'), table_name='dim_unit')
    op.drop_table('dim_unit')
    op.drop_table('user_sites')
    op.drop_index(op.f('ix_uploads_month'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_table('display_devices')
    op.drop_table('users')
    op.drop_table('targets')
    op.drop_table('tank_site')
    op.drop_table('standby_group')
    op.drop_table('sites')
    op.drop_table('pm_interval')
    op.drop_index(op.f('ix_plan_produksi_site'), table_name='plan_produksi')
    op.drop_table('plan_produksi')
    op.drop_table('id_alias')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
